Issue #96: Completed revert operation support for "remove method" operation.            Added sortable refresh on element remove BUT I anyway I could see error messages in logs after manipulations with methods "remove":
jquery.js (line 1718)

TypeError: elem is null
[Break On This Error]

var noData = elem.nodeName && jQuery.noData[ elem.nodeName.toLowerCase() ];